// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YuNotes.Data;

#nullable disable

namespace YuNotes.Migrations
{
    [DbContext(typeof(NotesContext))]
    [Migration("20241112223114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("YuNotes.Models.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("YuNotes.Models.NoteGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dce9243e-ff2a-4cf6-8ed0-6500bb59667d"),
                            Name = "Work"
                        },
                        new
                        {
                            Id = new Guid("c71d33fb-4879-4e66-b5f3-2e642ad8c092"),
                            Name = "Life"
                        },
                        new
                        {
                            Id = new Guid("0ecb5278-cf64-446e-9908-56b92e4d7286"),
                            Name = "Personal"
                        },
                        new
                        {
                            Id = new Guid("c6b2faf3-18e2-4793-83c7-918d1e92f826"),
                            Name = "Travel"
                        });
                });

            modelBuilder.Entity("YuNotes.Models.Note", b =>
                {
                    b.HasOne("YuNotes.Models.NoteGroup", "Group")
                        .WithMany("Notes")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("YuNotes.Models.NoteGroup", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
